name: Main

on:
  workflow_dispatch:
    inputs:
      body:
        default: ""
      test:
        default: false
  pull_request_target:

jobs:
  vm-job:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Set up aws-cli
      uses: unfor19/install-aws-cli-action@v1
      id: install-aws-cli
      with:
        version: 2
        run: aws --version
        shell: bash

    - name: Set up LocalStack
      run: |
        cp -avr .aws/ ~/
        docker-compose -f docker-compose.localstack.yml up -d
        while ! curl -s http://localhost:4566 > /dev/null; do echo waiting for localstack; sleep 3; done;
        aws --endpoint-url=http://localhost:4566 sns create-topic --name liam_TestProducer

    - name: Build
      env:
        RAILS_ENV: test
      run: |
        gem install bundler -v 2.1.4 -N
        bundle _2.1.4_ install --jobs 4 --retry 3

    - name: Run tests
      run: |
        RAILS_ENV=test bundle exec rspec -fd
